"""Add avatar and followed relationships

Revision ID: 35548e48e533
Revises: 0849195414ab
Create Date: 2022-05-14 02:23:38.965970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35548e48e533'
down_revision = '0849195414ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_table('followers')
    # ### end Alembic commands ###
